version: '2'
services:
  db:
    build: ./db
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker

  api:
    build:
      context: ./api
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./api:/go/src/github.com/user/goweb5/api
    ports:
      - "5000:8080"
    links:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./frontend:/go/src/github.com/user/goweb5/frontend
    ports:
      - "5001:8082"

  admin:
    build:
      context: ./admin
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./admin:/go/src/github.com/user/goweb5/admin
    ports:
      - "5002:8081"
